---
- name: Check required variables
  ansible.builtin.fail:
    msg: "Variable {{ item }} is not defined"
  when: item not in vars
  with_items: "{{ required_vars }}"

- name: Create ~/install directory
  ansible.builtin.file:
    path: ~/install
    state: directory
    mode: "0755"

- name: Enable HTTP traffic on firewall
  ansible.posix.firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled
  become: yes

- name: Enable HTTPS traffic on firewall
  ansible.posix.firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled
  become: yes

- name: Allow httpd to read user content
  ansible.posix.seboolean:
    name: httpd_read_user_content
    state: yes
    persistent: yes
  notify: Restart apache service
  become: yes

- name: Set up Apache
  ansible.builtin.import_tasks:
    file: set_up_apache.yml

- name: Install additional packages
  ansible.builtin.package:
    name:
      - "{{ rsync_package }}"
    state: present
  become: yes

- name: Setup {{ web_apps_root }} directory
  ansible.builtin.import_tasks:
    file: setup_webapps_directory.yml
