---
- name: Install apache
  ansible.builtin.package:
    name: "{{ apache_package }}"
    state: present
  notify:
    - Enable apache service (start on boot)
  become: yes

- name: Create ~/install directory
  ansible.builtin.file:
    path: ~/install
    state: directory
    mode: '0755'

- name: Install mod_wsgi
  ansible.builtin.import_tasks:
    file: install_mod_wsgi.yml

- name: Install additional packages
  ansible.builtin.package:
    name:
      - "{{ rsync_package }}"
    state: present
  become: yes

- name: Enable HTTP traffic on firewall
  ansible.posix.firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled
  become: yes
