---
- name: Enable apache service (start on boot)
  ansible.builtin.service:
    name: "{{ apache_service }}"
    enabled: yes
  become: yes

- name: Restart apache service
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: restarted
  become: yes
