---
- name: Copy website sources
  synchronize:
    src: ../caloru/
    dest: /home/{{ ansible_user }}/caloru/
    dest_port: "{{ ansible_ssh_port }}"
    archive: yes

- name: Create Python virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv ~/caloru/venv
    creates: ~/caloru/venv

- name: Install Python requirements
  ansible.builtin.shell: |
    source ~/caloru/venv/bin/activate
    pip install --upgrade pip==21.3.1
    pip install -r ~/caloru/requirements.txt
