repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/pylint
    rev: 84b06bb89750b5b557057508fcc294d8af7a469b
    hooks:
      - id: pylint
        additional_dependencies:
          - . # <-- that makes it install current project
          - Django
        args: ["--disable=C0114,C0115,C0116", "--generated-members=objects"]
  - repo: local
    hooks:
      - id: test
        name: Run Caloru tests
        entry: bash
        args: ["-c", "cd ./caloru && python3 -m venv ./.tmp_venv && source ./.tmp_venv/bin/activate && pip3 freeze && pip3 install -r requirements.txt > /dev/null 2>&1 && python3 manage.py test && rm -r ./.tmp_venv"]
        language: system
