repos:
  - repo: https://github.com/rhysd/actionlint
    rev: 9e907dcce268a56faccbbac5d65d8eb2126f2f78
    hooks:
      - id: actionlint
  - repo: https://github.com/ansible/ansible-lint
    rev: 9b5bad4450e7f2c1f5c61267e4084baebef4bf85
    hooks:
      - id: ansible-lint
  - repo: https://github.com/psf/black
    rev: 0e9d29ab73d608a79028e22a713ee717b5dcca96
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/pylint
    rev: 60a2db21d8ff6ca59e32f632ca501305c0403fe5
    hooks:
      - id: pylint
        additional_dependencies:
          - . # <-- that makes it install current project
          - Django
        args: ["--disable=C0114,C0115,C0116", "--generated-members=objects"]
  - repo: https://github.com/PyCQA/flake8
    rev: 0610cd2db8b49cbbb76b3c6c6533933548af65ad
    hooks:
      - id: flake8
        args: [--max-line-length=80]
