---
all:
  hosts:
    webserver:
      ansible_host: "{{ lookup('env', 'OCI_HOST') }}"
      ansible_port: 22
      ansible_user: opc

      apache_package: httpd-2.4.37-47.0.2.module+el8.6.0+20724+119b489d.2
      apache_service: httpd

      mod_wsgi_version: 4.9.4
      mod_wsgi_deps:
        - httpd-devel
        - redhat-rpm-config
        - python3-devel

      rsync_package: rsync-3.1.3-19.el8
