# Generated by Django 5.2.6 on 2025-10-04 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import foods.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("portion_weight", models.PositiveIntegerField()),
                ("portion_name", models.CharField(max_length=255)),
                (
                    "energy",
                    models.FloatField(validators=[foods.models._MinValueValidator(0)]),
                ),
                (
                    "protein",
                    models.FloatField(validators=[foods.models._MinValueValidator(0)]),
                ),
                (
                    "carbs",
                    models.FloatField(validators=[foods.models._MinValueValidator(0)]),
                ),
                (
                    "fat",
                    models.FloatField(validators=[foods.models._MinValueValidator(0)]),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackedFoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("meal", models.CharField(max_length=255)),
                ("amount", models.PositiveIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="foods.fooditem"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
