# Generated by Django 5.2.6 on 2025-10-05 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedfooditem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="foods.fooditem"
            ),
        ),
    ]
