version: "3.4"

services:
  caloru:
    image: caloru
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: uvicorn --reload caloru.asgi:application --host 0.0.0.0 --port 8000
    env_file:
      - .env
    working_dir: /app/caloru
    volumes:
      - ..:/app
