version: "3.4"

services:
  caloru:
    image: caloru
    ports:
      - 127.0.0.1:8000:8000
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: uvicorn --reload caloru.asgi:application --host 0.0.0.0 --port 8000
    env_file:
      - .env
    working_dir: /app/caloru
    volumes:
      - ..:/app

  db:
    image: library/postgres:15-alpine
    restart: unless-stopped
    volumes:
      - caloru-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=caloru
      - POSTGRES_PASSWORD=caloru

volumes:
  caloru-db:
    driver: local
