---
- name: Deploy caloru app
  hosts: webserver
  tasks:

  - name: Check server availability
    ping:

  - name: Import the caloruapp role
    import_role:
      name: caloruapp
    vars:
      web_apps_root: "/home/webapps"
