---
- name: Configure the webserver for the caloru web app
  hosts: webserver
  tasks:

  - name: Check server availability
    ping:

  - name: Include the webserver role
    import_role:
      name: webserver
