---
- name: Configure a VM to host a static HTML website
  hosts: "{{ apache_server }}"
  tasks:

  - name: Check server availability
    ping:

  - name: Install apache
    package:
      name: "{{ apache_package }}"
      state: present
    register: apache_installation
    become: yes

  - name: Install additional packages
    package:
      name:
        - rsync
      state: latest
    become: yes

  - name: Enable apache service (start on boot)
    service:
      name: "{{ apache_service }}"
      enabled: yes
    become: yes
