name: Caloru integration workflow

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: 3.13

      - name: Install ruff
        run: pip install ruff==0.13.0

      - name: Format
        run: |
          ruff format
          ruff check --select I

      - name: Lint
        run: ruff check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build . --tag caloru:$(date +%s)
