---
name: 'Deploy to Google Compute Engine'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy_to_gce:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.OCI_SSH_KEY }}" > ~/.ssh/oci_ssh_key

    - name: Verify SSH host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OCI_SSH_HOST }}
        username: opc
        script: echo 'Verify host'

    - name: Setup the VM using ansible
      working-directory: ./ansible
      run: ansible-playbook vm_setup.yml -e apache_server=oracle_cloud_vm