---
name: 'Deploy to Google Compute Engine'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PROJECT_ID: sandbox-351818
  GCE_INSTANCE: todo-list-instance
  GCE_INSTANCE_ZONE: us-central1-a

jobs:
  deploy_to_gce:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: echo "${{ secrets.OCI_SSH_KEY }}" > ~/.ssh/oci_ssh_key

    - name: Verify SSH host
      run: ssh -o StrictHostKeyChecking=no opc@{{}} "echo 'Verify host'"

    - name: Setup the VM using ansible
      working-directory: ./ansible
      run: ansible-playbook vm_setup.yml -e apache_server=oracle_cloud_vm