---
name: Deploy caloru app

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    # don't run if commit message contains '[nolint]'
    if: "!contains(github.event.commits[0].message, '[nolint]')"

    name: Lint code base with Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run Super Linter
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_MARKDOWN: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_ANSIBLE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  deploy:
    name: Deploy solution to Oracle Cloud VM 
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Add secret masks
      run: echo "::add-mask::${{ secrets.OCI_SSH_HOST }}" 

    - name: Checkout
      uses: actions/checkout@v3

    - name: Verify SSH host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OCI_SSH_HOST }}
        username: opc
        key: ${{ secrets.OCI_SSH_KEY }}
        script: echo 'Verify host'

    - name: Store ssh key in agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.OCI_SSH_KEY }}

    - name: Setup web server
      env:
        OCI_HOST: ${{ secrets.OCI_SSH_HOST }}
        ANSIBLE_HOST_KEY_CHECKING: False
      working-directory: ./ansible
      run: ansible-playbook -i inventory/oracle_cloud.yml setup_webserver.yml 

    - name: Deploy caloru app
      env:
        OCI_HOST: ${{ secrets.OCI_SSH_HOST }}
        ANSIBLE_HOST_KEY_CHECKING: False
      working-directory: ./ansible
      run: ansible-playbook -i inventory/oracle_cloud.yml deploy_app.yml 
