---
name: 'Deploy to Google Compute Engine'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy_to_gce:
    runs-on: ubuntu-latest

    steps:
    - name: Add secret masks
      run: echo "::add-mask::${{ secrets.OCI_SSH_HOST }}" 

    - name: Checkout
      uses: actions/checkout@v3

    - name: Verify SSH host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OCI_SSH_HOST }}
        username: opc
        key: ${{ secrets.OCI_SSH_KEY }}
        script: echo 'Verify host'

    - name: Store ssh key in agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.OCI_SSH_KEY }}

    - name: Setup the VM using ansible
      env:
        OCI_HOST: ${{ secrets.OCI_SSH_HOST }}
        ANSIBLE_HOST_KEY_CHECKING: False
      working-directory: ./ansible
      run: ansible-playbook -vvv vm_setup.yml -e apache_server=oracle_cloud_vm